[package]
name = "osrm"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
osrm-sys = { path = "../osrm-sys", version = "0.1.0" }
thiserror = "2.0.12"
derive_builder = "0.20.2"
dotenvy = "0.15.7"

